### ISSUE TITLE
Aqara Smart Button no longer working

### ISSUE THREAD

**Issue by oneseventhree** [azogue/eventsensor#21]
Hi,
For some reason my Aqara Smart button is showing up as the CUBE I have:

<img width="401" alt="Screen Shot 2020-11-17 at 5 48 05 pm" src="https://user-images.githubusercontent.com/15043282/99361649-87cf8980-2906-11eb-8baf-96bd05e8d554.png">
<img width="583" alt="Screen Shot 2020-11-17 at 5 48 55 pm" src="https://user-images.githubusercontent.com/15043282/99361669-8f8f2e00-2906-11eb-86e0-abdb465174dd.png">

When I delete the EventSensor sensor I can see it working and all automations work too:
<img width="478" alt="Screen Shot 2020-11-17 at 5 48 17 pm" src="https://user-images.githubusercontent.com/15043282/99361744-acc3fc80-2906-11eb-8139-e134f5c24141.png">

When I try and set it up again it reverts to the first two photos and is shown as a cube and no automations work.

This is a new bug but I am not sure when it stopped working,

Is this a known problem?

Thanks for a great integration nonetheless!

**Comment by azogue** [comment]
Hi @oneseventhree, sorry for the late answer... did you solve your issue?

In your 1st screenshot the `Unique ID` of the deCONZ device is different from the one in the 3rd screenshot, maybe the `id: living_room_table_switch` is shared in 2 devices, so both are being processed?

I'd try by filtering the event using the `unique_id` instead of the `id`

**Comment by azogue** [comment]
Closing this one, as it was a config problem, not an issue with the integration logic
