### ISSUE TITLE
Custom state mapping can't be removed

### ISSUE THREAD

**Issue by GH2user** [azogue/eventsensor#8]
Hi azopgue,

Noted that once a custom state mapping is made you can't remove it.
If you remove it they still show up, you can however reduce the number of mappings to 1.

Using HA 108.8; go into integrations and select the event sensor you want, click the cogwheel (settings) top right and adjust the custom state mapping, click save. reopen the settings.

**Comment by azogue** [comment]
Hi @GH2user, good catch!

I'll try to fix it, but, in the meanwhile, **use a simple " " space to fill the field** and save, that will do it.

**Comment by azogue** [comment]
To fix this would involve A LOT of change in the validation process for the config flows in HA, so not walking that path.

We are using the `OptionsFlow` in an unorthodox way, as we fill the form with the actual data to edit the config entry (that is not the options flow mission).

To do that we set as _default value_ the current one, so, because these fields are optional (event data filter and the state map), if left empty (:= equal to `None`), the default value plays to substitute the null value with the default one, which is the actual one :), so nothing changes!

**Pressing the space bar does the trick**, so no big deal. I'm closing this one :)
